/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class indi_whc_webandcv_Java2Cpp */

#ifndef _Included_indi_whc_webandcv_Java2Cpp
#define _Included_indi_whc_webandcv_Java2Cpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     indi_whc_webandcv_Java2Cpp
 * Method:    GetDeviceSerialNum
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_indi_whc_webandcv_Java2Cpp_GetDeviceSerialNum
  (JNIEnv *, jclass);

/*
 * Class:     indi_whc_webandcv_Java2Cpp
 * Method:    GetRelayNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_indi_whc_webandcv_Java2Cpp_GetRelayNum
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
